### ISSUE TITLE
Parameter with ceil, floor, or round

### ISSUE THREAD

**Issue by mckinsel** [dnanexus/dxWDL#112]
The `disk` input to WDL tasks defined in [here](https://github.com/HumanCellAtlas/skylab/blob/master/library/tasks/HISAT2.wdl) has a `ceil`. Currently, dxWDL will build these tasks, but then during execution it throws `java.lang.RuntimeException: Variable disk is unbound`.

**Comment by orodeh** [comment]
@mckinsel, is this still a problem with dxWDL 0.63?

**Comment by orodeh** [comment]
I believe this is fixed in the development branch. Release 0.65 should ship with this fix.

**Comment by mckinsel** [comment]
Hey @orodeh, I think I'm still seeing a possibly similar issue with 0.66.1 . When I try to run [this task](https://github.com/HumanCellAtlas/skylab/blob/master/library/tasks/HISAT2.wdl#L94), I get
```
java.lang.RuntimeException: Call HISAT2Transcriptome does not have a binding for required variable preemptible.
```
I'm calling it from [here](https://github.com/HumanCellAtlas/skylab/blob/master/pipelines/smartseq2_single_sample/SmartSeq2SingleSample.wdl#L92), so the value for `preemptible` should be the default. Also, I think the correct behavior is for dnanexus to just ignore that value in the `runtime` block anyway.

**Comment by orodeh** [comment]
@mckinsel, what happens if you provide `preemptible` with a value at the call site, say `preemptible=1`. Does this still error out?

**Comment by mckinsel** [comment]
Yeah, specifying all the default values in the main workflow fixes it. I think this is basically #141

**Comment by orodeh** [comment]
Thanks, I'll focus on #141, and leave this issue closed.

**Comment by orodeh** [comment]
@mckinsel Looking deeper, it is slightly different than #141. I tried reproducing the problem with a simplified workflow, which works (see below). Do you have a  reduced example that reproduces the issue? I used dxWDL v0.67, but I think it should also work in 0.66.1. 

Here is the reduced workflow: 
```wdl
workflow hello_wf {
    call hello
    call hello as hello_james { input: who = "James", preemptible = 1 }

    output {
        String hello_result = hello.result
        Int hello_p = hello.p
        String hello_james_result = hello_james.result
	Int hello_james_p = hello_james.p
    }
}

task hello {
    String who = "world"
    Int preemptible = 5

    command {
	echo "Hello, ${who}"
    }
    runtime {
	preemptible: preemptible
	maxRetries: 5
    }
    output {
	String result = read_string(stdout())
	Int p = preemptible
    }
}
```

The `hello_wf` workflow checks what happens when you call a task with/without setting default arguments. In both cases, I get correct results. 

```json
{
  "hello_wf.hello_result": "Hello, world",
  "hello_wf.hello_p": 1,
  "hello_wf.hello_james_result": "Hello, James",
  "hello_wf.hello_james_p": 5
}
```

**Comment by mckinsel** [comment]
Yeah I'm actually having some trouble reproducing it outside of that exact set of circumstances. One thing that I'm doing that's a little odd is running dxWDL from within a dnanexus job. So, I set DX_WORKSPACE_ID and DX_PROJECT_CONTEXT_ID to the id of the containing project, run dxWDL, and then run the resulting workflow with the inputs json file produced by dxWDL.

**Comment by orodeh** [comment]
I thought about, but haven't been able to see how these settings would affect the dxWDL output. Of course, I might be wrong.

**Comment by mckinsel** [comment]
Okay here's a somewhat reduced example:

*test_smartseq2_single_sample_PR.wdl*
```
import "SmartSeq2SingleSample.wdl" as target_wdl

# this task will be run by the jenkins script that gets executed on our PRs.
workflow TestSmartSeq2SingleCellPR {
  File fastq1
  String output_name

  call target_wdl.SmartSeq2SingleCell as target_workflow {
    input:
      fastq1 = fastq1,
      output_name = output_name
  }
}
```

*SmartSeq2SingleSample.wdl*
```
import "HISAT2.wdl" as HISAT2

workflow SmartSeq2SingleCell {
  File fastq1
  String output_name
  Int max_retries = 0

  String quality_control_output_basename = output_name + "_qc"

  call HISAT2.HISAT2PairedEnd {
    input:
      fastq1 = fastq1,
      output_basename = quality_control_output_basename,
      max_retries = max_retries
  }

  output {
    File aligned_bam = HISAT2PairedEnd.output_bam
  }
}
```

*HISAT2.wdl*
```
task HISAT2PairedEnd {
  File fastq1
  String output_basename

  String docker = "quay.io/humancellatlas/secondary-analysis-hisat2:v0.2.2-2-2.1.0"
  Int machine_mem_mb = 15000
  Int cpu = 4
  Int disk = ceil((size(fastq1, "GB")))
  Int preemptible = 5
  Int max_retries = 0

  command {
    set -e
    touch output.bam
  }

  runtime {
    docker: docker
    memory: "${machine_mem_mb} MB"
    disks: "local-disk ${disk} HDD"
    cpu: cpu
    preemptible: preemptible
    maxRetries: max_retries
  }

  output {
    File output_bam = "output.bam"
  }
}
```

This produces an applet named "SmartSeq2SingleCell_HISAT2PairedEnd", which is what fails. If I replace the "quality_control_output_basename" with a static string, such an applet is not created, and the whole thing succeeds.

**Comment by orodeh** [comment]
Thanks! I managed to reproduce this behavior.

**Comment by orodeh** [comment]
Fixed in version 0.68. The problem was that the workflow-fragment runner has a runtime check that is too strict. Even though `preemptible` has a default value in `HISAT2`, the runner insisted that a value for it be provided in the call.  A complication is that `preemptible` is a potential input, since draft-2 doesn't have well defined inputs.

If "quality_control_output_basename" is a static string, the call is optimized into a dx:workflow stage, and there is no need for a runner. This also save the "SmartSeq2SingleCell_HISAT2PairedEnd" dx:applet.

**Comment by mckinsel** [comment]
Thanks @orodeh ! Right now I'm getting a "Project dxWDL not found". I'm guessing that means I need to wait a little bit?

**Comment by orodeh** [comment]
@mckinsel You have the right version; this error is not supposed to happen. dxWDL (should be) a public project that holds all the versions of the runtime asset. Can you see it?

**Comment by mckinsel** [comment]
So I see this:
```
$ dx find projects --public --name dxWDL
project-F2gg1xj0KFB7BqB65QJG3GY3 : dxWDL (VIEW)
```
but also
```
$ java -jar ../dxWDL-0.68.jar compile test_smartseq2_single_sample_PR.wdl -inputs inputs.json -destination project-F9GG0VQ05pkypzKYBX0g2yzV:/8853b11d-cb6c-40d4-a85e-c9959ebc9060
Empty output section, no outputs will be generated
Runtime attribute preemptible for task HISAT2PairedEnd is unknown
Runtime attribute maxRetries for task HISAT2PairedEnd is unknown
java.lang.Exception: Project dxWDL not found
        at dxWDL.DxPath$.lookupProject(DxPath.scala:52)
        at dxWDL.compiler.Top$.getAssetId(Top.scala:187)
        at dxWDL.compiler.Top$.compileNative(Top.scala:237)
        at dxWDL.compiler.Top$.apply(Top.scala:274)
        at dxWDL.Main$.compile(Main.scala:385)
        at dxWDL.Main$.dispatchCommand(Main.scala:571)
        at dxWDL.Main$.delayedEndpoint$dxWDL$Main$1(Main.scala:624)
        at dxWDL.Main$delayedInit$body.apply(Main.scala:12)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at dxWDL.Main$.main(Main.scala:12)
        at dxWDL.Main.main(Main.scala)
```

**Comment by orodeh** [comment]
Alright, I will look into it.

**Comment by orodeh** [comment]
I suspect a permissions problem.

**Comment by mckinsel** [comment]
fwiw, it works fine with v0.67.

**Comment by mckinsel** [comment]
Hey it worked! Thanks for the help.

**Comment by orodeh** [comment]
Thanks for sticking with it. This took several rounds to get right.
